name: Fetch and Insert Tweets

on:
  schedule:
    - cron: '0 * * * *'  # Roda a cada hora
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name:  Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up environment variables
        run: |
            echo "BEARER_TOKEN=${{ secrets.BEARER_TOKEN }}" >> $GITHUB_ENV
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
  
      - name: Debug environment variables
        run: |
            echo "BEARER_TOKEN is set to: ${BEARER_TOKEN}"
            env | grep BEARER
      - name: Run script
        run: python get_tweets.py
