name: Test BEARER_TOKEN

on:
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  test-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up environment variables
        run: |
          echo "BEARER_TOKEN=${{ secrets.BEARER_TOKEN }}" >> $GITHUB_ENV

      - name: Debug BEARER_TOKEN
        run: | 
            echo "Token is set to: ${BEARER_TOKEN}"

      - name: Run test script
        run: python test_env.py
